server.port=8080

spring.datasource.url=jdbc:sqlserver://DHSKLPDTAI290;instanceName=SQLEXPRESS;databaseName=infovault;encrypt=true;trustServerCertificate=true
spring.datasource.username=user
spring.datasource.password=Strongpassword123

file.storage.path=C:/Users/2396/Downloads/infovault/uploads/

# Important for production
logging.level.org.springframework=WARN
logging.level.org.hibernate=ERROR